Epsilon/Epsilon.Web/Controllers/PropertyInfoController.cs
using Epsilon.Logic.Constants;
using Epsilon.Logic.Constants.Enums;
using Epsilon.Logic.Services.Interfaces;
using Epsilon.Resources.Common;
using Epsilon.Web.Controllers.BaseControllers;
using Epsilon.Web.Models.ViewModels.PropertyInfo;
using Epsilon.Web.Models.ViewModels.Shared;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Epsilon.Web.Controllers
{
    public class PropertyInfoController : BaseMvcController
    {
        public const string MY_EXPLORED_PROPERTIES_SUMMARY_ACTION = "MyExploredPropertiesSummary";

        private readonly ICountryService _countryService;
        private readonly IAddressService _addressService;
        private readonly IPropertyInfoAccessService _propertyInfoAccessService;
        private readonly ITokenRewardService _tokenRewardService;

        public PropertyInfoController(
            ICountryService countryService,
            IAddressService addressService,
            IPropertyInfoAccessService propertyInfoAccessService,
            ITokenRewardService tokenRewardService)
        {
            _countryService = countryService;
            _addressService = addressService;
            _propertyInfoAccessService = propertyInfoAccessService;
            _tokenRewardService = tokenRewardService;
        }

        public ActionResult SearchProperty()
        {
            var availableCountries = _countryService.GetAvailableCountries();
            var model = new SearchPropertyViewModel
            {
                AvailableCountries = availableCountries
            };
            return View(model);
        }

        public async Task<ActionResult> GainAccess(Guid id)
        {
            var addressUniqueId = id;

            var hasCompletedSubmissions = await _addressService.AddressHasCompleteSubmissions(addressUniqueId);
            if (!hasCompletedSubmissions)
            {
                Danger(CommonResources.GenericInvalidActionMessage, true);
                return RedirectHome(false);
            }

            var entity = await _addressService.GetAddress(addressUniqueId);
            var existingAccessUniqueId = await _propertyInfoAccessService.GetExistingUnexpiredAccessUniqueId(GetUserId(), addressUniqueId);
            var model = new GainAccessViewModel
            {
                AccessUniqueId = Guid.NewGuid(),
                AddressDetails = AddressDetailsViewModel.FromEntity(entity),
                TokensCost = _tokenRewardService.GetCurrentReward(TokenRewardKey.SpendPerPropertyInfoAccess).AbsValue,
                ExistingUnexpiredAccessUniqueId = existingAccessUniqueId
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> GainAccessConfirmed(Guid accessUniqueId, Guid selectedAddressUniqueId)
        {
            var outcome = await _propertyInfoAccessService
                .Create(GetUserId(), GetUserIpAddress(), accessUniqueId, selectedAddressUniqueId);
            if (outcome.IsRejected)
            {
                Danger(outcome.RejectionReason, true);
                return RedirectHome(false);
            }
            else
            {
                PresentUiAlerts(outcome.UiAlerts, true);
                return RedirectToAction("ViewInfo", new { id = outcome.PropertyInfoAccessUniqueId, returnToSummary = false });
            }      
        }

        [HttpGet]
        public async Task<ActionResult> ViewInfo(Guid id, bool returnToSummary)
        {
            var accessUniqueId = id;
            var getInfoOutcome =
                await _propertyInfoAccessService.GetInfo(GetUserId(), accessUniqueId);

            if (getInfoOutcome.IsRejected)
            {
                Danger(getInfoOutcome.RejectionReason, true);
                return RedirectHome(returnToSummary);
            }

            var model = new ViewPropertyViewModel
            {
                PropertyInfo = getInfoOutcome.PropertyInfo,
                ReturnToSummary = returnToSummary
            };
            return View(model);
        }

        public ActionResult MyExploredPropertiesSummary()
        {
            return View();
        }

        private ActionResult RedirectHome(bool returnToSummary)
        {
            if (returnToSummary)
            {
                return RedirectToAction(MY_EXPLORED_PROPERTIES_SUMMARY_ACTION);
            }

            return RedirectToAction(
                AppConstant.AUTHENTICATED_USER_HOME_ACTION,
                AppConstant.AUTHENTICATED_USER_HOME_CONTROLLER);
        }
    }
}

Epsilon/Epsilon.Web/Controllers/SubmissionController.cs
using Epsilon.Logic.Constants;
using Epsilon.Logic.Forms.Submission;
using Epsilon.Logic.Services.Interfaces;
using Epsilon.Resources.Common;
using Epsilon.Web.Controllers.BaseControllers;
using Epsilon.Web.Models.ViewModels.Shared;
using Epsilon.Web.Models.ViewModels.Submission;
using Microsoft.AspNet.Identity;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Epsilon.Web.Controllers
{
    public class SubmissionController : BaseMvcController
    {
        public const string MY_SUBMISSIONS_SUMMARY_ACTION = "MySubmissionsSummary";

        private readonly ICountryService _countryService;
        private readonly ICurrencyService _currencyService;
        private readonly IAddressService _addressService;
        private readonly ITenancyDetailsSubmissionService _tenancyDetailsSubmissionService;

        public SubmissionController(
            ICountryService countryService,
            ICurrencyService currencyService,
            IAddressService addressService,
            ITenancyDetailsSubmissionService tenancyDetailsSubmissionService)
        {
            _countryService = countryService;
            _currencyService = currencyService;
            _addressService = addressService;
            _tenancyDetailsSubmissionService = tenancyDetailsSubmissionService;
        }

        public ActionResult SearchAddress()
        {
            var availableCountries = _countryService.GetAvailableCountries();
            var model = new SearchAddressViewModel
            {
                AvailableCountries = availableCountries
            };
            return View(model);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddAddress(string countryId, string postcode)
        {
            countryId = countryId.ToUpperInvariant();

            var countries = _countryService.GetAvailableCountries();
            ViewBag.CountryId = new SelectList(countries, "Id", AppConstant.COUNTRY_DISPLAY_FIELD, countryId);

            var model = new AddressForm
            {
                UniqueId = Guid.NewGuid(),
                CountryId = countryId,
                Postcode = postcode
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SaveAddress(AddressForm address)
        {
            if (ModelState.IsValid)
            {
                var outcome = await _addressService.AddAddress(User.Identity.GetUserId(), GetUserIpAddress(), address);
                if (outcome.IsRejected)
                {
                    Danger(outcome.RejectionReason, true);
                    if (outcome.ReturnToForm)
                    {
                        ViewBag.CountryId = new SelectList(_countryService.GetAvailableCountries(), "Id", AppConstant.COUNTRY_DISPLAY_FIELD, address.CountryId);
                        return View("AddAddress", address);
                    }
                    else
                    {
                        return RedirectToAction(
                            AppConstant.AUTHENTICATED_USER_HOME_ACTION,
                            AppConstant.AUTHENTICATED_USER_HOME_CONTROLLER);
                    }
                }
                
                return RedirectToAction("UseAddress", new { id = address.UniqueId });
            }

            ViewBag.CountryId = new SelectList(_countryService.GetAvailableCountries(), "Id", AppConstant.COUNTRY_DISPLAY_FIELD, address.CountryId);
            return View("AddAddress", address);
        }

        [HttpGet]
        public async Task<ActionResult> UseAddress(Guid id)
        {
            var addressUniqueId = id;
            var entity = await _addressService.GetAddress(addressUniqueId);
            var model = new UseAddressViewModel
            {
                SubmissionUniqueId = Guid.NewGuid(),
                AddressDetails = AddressDetailsViewModel.FromEntity(entity)
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> UseAddressConfirmed(Guid submissionUniqueId, Guid selectedAddressUniqueId)
        {
            var outcome = await _tenancyDetailsSubmissionService
                .Create(GetUserId(), GetUserIpAddress(), submissionUniqueId, selectedAddressUniqueId);
            if (outcome.IsRejected)
            {
                Danger(outcome.RejectionReason, true);
            }
            else
            {
                PresentUiAlerts(outcome.UiAlerts, true);
            }

            return RedirectToAction(
                AppConstant.AUTHENTICATED_USER_HOME_ACTION,
                AppConstant.AUTHENTICATED_USER_HOME_CONTROLLER);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EnterVerificationCode(Guid submissionUniqueId, bool returnToSummary)
        {
            var getSubmissionAddressOutcome = await _tenancyDetailsSubmissionService.GetSubmissionAddress(GetUserId(), submissionUniqueId);
            if (getSubmissionAddressOutcome.SubmissionNotFound)
            {
                Danger(CommonResources.GenericInvalidRequestMessage, true);
                return RedirectHome(returnToSummary);
            }

            var model = new VerificationCodeForm
            {
                DisplayAddress = getSubmissionAddressOutcome.Address.FullAddress(),
                TenancyDetailsSubmissionUniqueId = submissionUniqueId,
                ReturnToSummary = returnToSummary
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EnterVerificationCodeSubmit(VerificationCodeForm form)
        {
            if (ModelState.IsValid)
            {
                var outcome = await _tenancyDetailsSubmissionService.EnterVerificationCode(GetUserId(), form);
                if (outcome.IsRejected)
                {
                    Danger(outcome.RejectionReason, true);
                    if (outcome.ReturnToForm)
                    {
                        return View("EnterVerificationCode", form);
                    }
                    else
                    {
                        return RedirectHome(form.ReturnToSummary);
                    }
                }

                PresentUiAlerts(outcome.UiAlerts, true);

                return RedirectHome(form.ReturnToSummary);
            }

            return View("EnterVerificationCode", form);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SubmitTenancyDetails(Guid submissionUniqueId, bool returnToSummary)
        {
            var getSubmissionAddressOutcome = await _tenancyDetailsSubmissionService.GetSubmissionAddress(GetUserId(), submissionUniqueId);
            if (getSubmissionAddressOutcome.SubmissionNotFound)
            {
                Danger(CommonResources.GenericInvalidRequestMessage, true);
                return RedirectHome(returnToSummary);
            }
            var currency = _currencyService.Get(getSubmissionAddressOutcome.Address.Country.CurrencyId);
            var model = new TenancyDetailsForm
            {
                DisplayAddress = getSubmissionAddressOutcome.Address.FullAddress(),
                TenancyDetailsSubmissionUniqueId = submissionUniqueId,
                ReturnToSummary = returnToSummary,
                CurrencySybmol = currency.Symbol
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SubmitTenancyDetailsSave(TenancyDetailsForm form)
        {
            if (ModelState.IsValid)
            {
                var outcome = await _tenancyDetailsSubmissionService.SubmitTenancyDetails(GetUserId(), form);
                if (outcome.IsRejected)
                {
                    Danger(outcome.RejectionReason, true);
                    if (outcome.ReturnToForm)
                    {
                        return View("SubmitTenancyDetails", form);
                    }
                    else
                    {
                        return RedirectHome(form.ReturnToSummary);
                    }
                }

                PresentUiAlerts(outcome.UiAlerts, true);

                return RedirectHome(form.ReturnToSummary);
            }

            return View("SubmitTenancyDetails", form);
        }

        [HttpGet]
        public ActionResult MySubmissionsSummary()
        {
            return View();
        }

        private ActionResult RedirectHome(bool returnToSummary)
        {
            if (returnToSummary)
            {
                return RedirectToAction(MY_SUBMISSIONS_SUMMARY_ACTION);
            }

            return RedirectToAction(
                AppConstant.AUTHENTICATED_USER_HOME_ACTION,
                AppConstant.AUTHENTICATED_USER_HOME_CONTROLLER);
        }
    }
}

Epsilon/Epsilon.Web/Controllers/UserHomeController.cs
using Epsilon.Web.Controllers.BaseControllers;
using System.Web.Mvc;

namespace Epsilon.Web.Controllers
{
    public class UserHomeController : BaseMvcController
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Epsilon/Epsilon.Web/Views/UserHome/Index.cshtml
@using Epsilon.Resources.Web.UserHome
@using Epsilon.Logic.Models

@{
    ViewBag.Title = UserHomeResources.Index_PageTitle;

    var userInterfaceCustomisation = (UserInterfaceCustomisationModel) ViewBag.UserInterfaceCustomisation;
}

<hr />

<div class="row">
    <div class="col-md-8">
        <div>
            <my-submissions-summary limit-items-returned="true" is-summary-page="false" allow-caching="true" />
        </div>
        <div>
            <my-outgoing-verifications-summary limit-items-returned="true" is-summary-page="false" allow-caching="true"/>
        </div>
        <div>
            <my-explored-properties-summary limit-items-returned="true" is-summary-page="false" allow-caching="true" />
        </div>
    </div>

    <div class="col-md-4">
        @if (userInterfaceCustomisation.CanCreateTenancyDetailsSubmission)
        {
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h4>
                    @(userInterfaceCustomisation.HasNoTenancyDetailsSubmissions ? 
                      UserHomeResources.SectionCreateSubmission_NoPreviousSubmissions_Header :
                      UserHomeResources.SectionCreateSubmission_Header)
                </h4>
            </div>
            <div class="panel-body">
                <p>
                    @(userInterfaceCustomisation.HasNoTenancyDetailsSubmissions ?
                      UserHomeResources.SectionCreateSubmission_NoPreviousSubmissions_Text :
                      UserHomeResources.SectionCreateSubmission_Text)
                </p>
                <p><a class="btn btn-primary" 
                      href="@Url.Action("SearchAddress", "Submission")">
                    @(userInterfaceCustomisation.HasNoTenancyDetailsSubmissions ?
                      UserHomeResources.SectionCreateSubmission_NoPreviousSubmissions_ButtonText :
                      UserHomeResources.SectionCreateSubmission_ButtonText) &raquo;
                   </a>
                </p>
            </div>
        </div>
        }
        @if (userInterfaceCustomisation.CanPickOutgoingVerification)
        {
        <div class="panel panel-primary">
            <div class="panel-heading"><h4>@UserHomeResources.SectionPickOutgoingVerification_Header</h4></div>
            <div class="panel-body">
                <p>@UserHomeResources.SectionPickOutgoingVerification_Text</p>
                <p>
                    @using (Html.BeginForm("Pick", "OutgoingVerification"))
                    {
                        @Html.AntiForgeryToken()
                        <input type="hidden" name="verificationUniqueId" value="@Guid.NewGuid()" />
                        <input type="hidden" name="returnToSummary" value="false" />
                        <input type="submit" value="@UserHomeResources.SectionPickOutgoingVerification_ButtonText &raquo"
                               data-click-once
                               class="btn btn-primary" />
                    }
                </p>
            </div>
        </div>
        }
        <div class="panel panel-primary">
            <div class="panel-heading"><h4>@UserHomeResources.SectionExploreProperties_Header</h4></div>
            <div class="panel-body">
                <p>@UserHomeResources.SectionExploreProperties_Text</p>
                <p>
                    <a class="btn btn-primary" href="@Url.Action("SearchProperty", "PropertyInfo")">
                        @UserHomeResources.SectionExploreProperties_ButtonText &raquo;
                    </a>
                </p>
            </div>
        </div>
    </div>
</div>