Epsilon/Epsilon.Web/Models/ViewModels/OutgoingVerification/InstructionsViewModel.cs
using Epsilon.Logic.Models;

namespace Epsilon.Web.Models.ViewModels.OutgoingVerification
{
    public class InstructionsViewModel
    {
        public OutgoingVerificationInstructionsModel Instructions { get; set; }
        public bool ReturnToSummary { get; set; }
    }
}

Epsilon/Epsilon.Web/Models/ViewModels/OutgoingVerification/PickOutgoingVerificationViewModel.cs
using System;

namespace Epsilon.Web.Models.ViewModels.OutgoingVerification
{
    public class PickOutgoingVerificationViewModel
    {
        public Guid VerificationUniqueId { get; set; }
        public bool ReturnToSummary { get; set; }
    }
}

Epsilon/Epsilon.Web/Controllers/ApiControllers/OutgoingVerificationController.cs
using Epsilon.Logic.JsonModels;
using Epsilon.Logic.Services.Interfaces;
using Epsilon.Web.Controllers.BaseControllers;
using System.Threading.Tasks;
using System.Web.Http;

namespace Epsilon.Web.Controllers.ApiControllers
{
    public class OutgoingVerificationController : BaseApiController
    {
        private readonly IOutgoingVerificationService _outgoingVerificationService;

        public OutgoingVerificationController(
            IOutgoingVerificationService outgoingVerificationService)
        {
            _outgoingVerificationService = outgoingVerificationService;
        }

        [HttpPost]
        public async Task<MyOutgoingVerificationsSummaryResponse> MyOutgoingVerificationsSummary(
            MyOutgoingVerificationsSummaryRequest request)
        {
            if (request.allowCaching)
                return await _outgoingVerificationService.GetUserOutgoingVerificationsSummaryWithCaching(GetUserId(), request.limitItemsReturned);

            return await _outgoingVerificationService.GetUserOutgoingVerificationsSummary(GetUserId(), request.limitItemsReturned);
        }
    }
}

Epsilon/Epsilon.Web/Controllers/OutgoingVerificationController.cs
using Epsilon.Logic.Constants;
using Epsilon.Logic.Services.Interfaces;
using Epsilon.Resources.Web.OutgoingVerification;
using Epsilon.Web.Controllers.BaseControllers;
using Epsilon.Web.Models.ViewModels.OutgoingVerification;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Epsilon.Web.Controllers
{
    public class OutgoingVerificationController : BaseMvcController
    {
        public const string MY_OUTGOING_VERIFICATIONS_SUMMARY_ACTION = "MyOutgoingVerificationsSummary";

        private readonly IOutgoingVerificationService _outgoingVerificationService;
        private readonly IUserResidenceService _userResidenceService;

        public OutgoingVerificationController(
            IOutgoingVerificationService outgoingVerificationService,
            IUserResidenceService userResidenceService)
        {
            _outgoingVerificationService = outgoingVerificationService;
            _userResidenceService = userResidenceService;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Pick(PickOutgoingVerificationViewModel model)
        {
            var userResidenceServiceResponse = await _userResidenceService.GetResidence(GetUserId());
            if (userResidenceServiceResponse.HasNoSubmissions)
            {
                Danger(OutgoingVerificationResources.Pick_CannotDetermineUserResidenceBecauseOfNoSubmissions_ErrorMessage, true);
                return RedirectHome(false);
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> PickConfirmed(Guid verificationUniqueId, bool returnToSummary)
        {
            var outcome = await _outgoingVerificationService.Pick(GetUserId(), GetUserIpAddress(), verificationUniqueId);
            if (outcome.IsRejected)
            {
                Danger(outcome.RejectionReason, true);
                return RedirectHome(returnToSummary);
            }
            else
            {
                PresentUiAlerts(outcome.UiAlerts, true);
                return RedirectToAction("Instructions", new { id = outcome.VerificationUniqueId, returnToSummary = returnToSummary });
            }
        }

        [HttpGet]
        public async Task<ActionResult> Instructions(Guid id, bool returnToSummary)
        {
            var verificationUniqueId = id;
            var getInstructionsOutcome =
                await _outgoingVerificationService.GetInstructions(GetUserId(), verificationUniqueId);

            if (getInstructionsOutcome.IsRejected)
            {
                Danger(getInstructionsOutcome.RejectionReason, true);
                return RedirectHome(returnToSummary);
            }

            var model = new InstructionsViewModel
            {
                Instructions = getInstructionsOutcome.Instructions,
                ReturnToSummary = returnToSummary
            };
            return View(model);
        }

        public async Task<ActionResult> PrintableVerificationMessage(Guid id)
        {
            var verificationUniqueId = id;
            var getVerificationMessageOutcome =
                await _outgoingVerificationService.GetVerificationMessage(GetUserId(), verificationUniqueId);

            if (getVerificationMessageOutcome.IsRejected)
            {
                Danger(getVerificationMessageOutcome.RejectionReason, true);
                return RedirectHome(false);
            }

            var model = getVerificationMessageOutcome.MessageArguments;
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> MarkAsSent(Guid verificationUniqueId, bool returnToSummary)
        {
            var outcome = await _outgoingVerificationService.MarkAsSent(GetUserId(), verificationUniqueId);
            if (outcome.IsRejected)
            {
                Danger(outcome.RejectionReason, true);
            }
            else
            {
                PresentUiAlerts(outcome.UiAlerts, true);
            }

            return RedirectHome(returnToSummary);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> MarkAddressAsInvalid(Guid verificationUniqueId, bool returnToSummary)
        {
            var outcome = await _outgoingVerificationService.MarkAddressAsInvalid(GetUserId(), verificationUniqueId);
            if (outcome.IsRejected)
            {
                Danger(outcome.RejectionReason, true);
            }
            else
            {
                PresentUiAlerts(outcome.UiAlerts, true);
            }
            
            return RedirectHome(returnToSummary);
        }

        public ActionResult MyOutgoingVerificationsSummary()
        {
            return View();
        }

        private ActionResult RedirectHome(bool returnToSummary)
        {
            if (returnToSummary)
            {
                return RedirectToAction(MY_OUTGOING_VERIFICATIONS_SUMMARY_ACTION);
            }

            return RedirectToAction(
                AppConstant.AUTHENTICATED_USER_HOME_ACTION,
                AppConstant.AUTHENTICATED_USER_HOME_CONTROLLER);
        }
    }
}

Epsilon/Epsilon.Web/Views/OutgoingVerification/Instructions.cshtml
@model Epsilon.Web.Models.ViewModels.OutgoingVerification.InstructionsViewModel
@using Epsilon.Resources.Web.OutgoingVerification
@using Epsilon.Resources.Common
@using Epsilon.Resources.Web.OutgoingVerification
@using Epsilon.Logic.Helpers.Interfaces
@using Epsilon.Logic.Constants.Enums
@using Epsilon.Logic.Helpers

@{
    ViewBag.Title = OutgoingVerificationResources.Instructions_PageTitle;

    var countryVariantResourceHelper = DependencyResolver.Current.GetService<ICountryVariantResourceHelper>();
    var countryVariantResources = countryVariantResourceHelper.GetVariantsForCountry(Model.Instructions.RecipientAddress.CountryId,
        new List<CountryVariantResourceName> {
            CountryVariantResourceName.OutgoingVerificationInstructions_AddressChecker_DisplayName,
            CountryVariantResourceName.OutgoingVerificationInstructions_AddressChecker_Url,
            CountryVariantResourceName.OutgoingVerificationInstructions_SendPaperMailOnlineProvider_1_DisplayName,
            CountryVariantResourceName.OutgoingVerificationInstructions_SendPaperMailOnlineProvider_1_Url,
            CountryVariantResourceName.OutgoingVerificationInstructions_SendPaperMailOnlineProvider_2_DisplayName,
            CountryVariantResourceName.OutgoingVerificationInstructions_SendPaperMailOnlineProvider_2_Url
        });
}

<h3>@OutgoingVerificationResources.Instructions_PageHeader</h3>
<hr />

<div class="form-horizontal">
    <div class="form-group">
        <label class="control-label col-md-3">@OutgoingVerificationResources.Instructions_RecipientAddressLabel</label>
        <div class="col-md-9">
            <div class="panel panel-primary panel-body">
                @Html.Partial("_VerificationRecipient", Model.Instructions.RecipientAddress)
            </div>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3">@OutgoingVerificationResources.Instructions_VerificationMessageLabel</label>
        <div class="col-md-9">
            <div class="panel panel-primary panel-body" >
                @Html.Partial("_VerificationMessage", Model.Instructions.MessageArguments)
            </div>
        </div>
    </div>
    <p class="col-md-offset-3">
        @Html.ActionLink("Printable version", "PrintableVerificationMessage", new { id = Model.Instructions.VerificationUniqueId },
            new { target = "_blank" })
    </p>
</div>

<hr />

<div class="panel panel-primary">
    <div class="panel-heading">
        <h4>@(CommonResources.Step1): @(OutgoingVerificationResources.Instructions_StepVerifyValidAddress_Header)</h4>
    </div>
    <div class="panel-body">
        @{
            // TODO_TEST_PANOS: Unit test that checks that everry country and and language has both of them defined (non-empty string).
            var addressCheckerUrl = countryVariantResources[EnumsHelper.CountryVariantResourceName
                .ToString(CountryVariantResourceName.OutgoingVerificationInstructions_AddressChecker_Url)];
            var addressCheckerDisplayName = countryVariantResources[EnumsHelper.CountryVariantResourceName
                .ToString(CountryVariantResourceName.OutgoingVerificationInstructions_AddressChecker_DisplayName)];
        }

        <p>
            @OutgoingVerificationResources.Instructions_StepVerifyValidAddress_Instructions <br />
            <ul>
                <li><a href="@addressCheckerUrl" target="_blank">@addressCheckerDisplayName</a></li>
            </ul>
        </p>

        @if (Model.Instructions.OtherUserHasMarkedAddressAsInvalid)
        {
            <div class="alert alert-danger">
                <p>
                    @OutgoingVerificationResources.Instructions_OtherUserHasMarkedAddressAsInvalid_Message
                </p>
            </div>
        }

        @if (Model.Instructions.CanMarkAddressAsInvalid)
        {
            <div>
                @using (Html.BeginForm("MarkAddressAsInvalid", "OutgoingVerification"))
                {
                    @Html.AntiForgeryToken()

                    <input type="hidden" name="verificationUniqueId" value="@Model.Instructions.VerificationUniqueId" />
                    <input type="hidden" name="returnToSummary" value="@Model.ReturnToSummary.ToString()" />
                    <button class="btn btn-danger" type="submit"
                            title="@OutgoingVerificationResources.Instructions_ActionMarkAddressAsInvalid_ButtonHoverText"
                            onclick="return confirm('@OutgoingVerificationResources.Instructions_ActionMarkAddressAsInvalid_ButtonConfirmationText')">
                        @OutgoingVerificationResources.Instructions_ActionMarkAddressAsInvalid_ButtonText
                    </button>
                }
            </div>
        }

    </div>
</div>

<div class="panel panel-primary">
    <div class="panel-heading">
        <h4>@(CommonResources.Step2): @(OutgoingVerificationResources.Instructions_StepSendVerification_Header)</h4>
    </div>
    <div class="panel-body">

        @{
            // TODO_TEST_PANOS: Unit test that checks that every country and and language has at least one provider defined (non-empty strings).
            var paperMailOnlinleProvider1Url = countryVariantResources[EnumsHelper.CountryVariantResourceName
                .ToString(CountryVariantResourceName.OutgoingVerificationInstructions_SendPaperMailOnlineProvider_1_Url)];
            var paperMailOnlinleProvider1DisplayName = countryVariantResources[EnumsHelper.CountryVariantResourceName
                .ToString(CountryVariantResourceName.OutgoingVerificationInstructions_SendPaperMailOnlineProvider_1_DisplayName)];
            var paperMailOnlinleProvider2Url = countryVariantResources[EnumsHelper.CountryVariantResourceName
                .ToString(CountryVariantResourceName.OutgoingVerificationInstructions_SendPaperMailOnlineProvider_2_Url)];
            var paperMailOnlinleProvider2DisplayName = countryVariantResources[EnumsHelper.CountryVariantResourceName
                .ToString(CountryVariantResourceName.OutgoingVerificationInstructions_SendPaperMailOnlineProvider_2_DisplayName)];
        }

        <p>
            @OutgoingVerificationResources.Instructions_StepSendVerification_Instructions
            
            <ul>
                @if (!string.IsNullOrWhiteSpace(paperMailOnlinleProvider1Url) && !string.IsNullOrWhiteSpace(paperMailOnlinleProvider1DisplayName))
            {
                    <li>
                        <a href="@paperMailOnlinleProvider1Url" target="_blank">@paperMailOnlinleProvider1DisplayName</a>
                    </li>
                }
                @if (!string.IsNullOrWhiteSpace(paperMailOnlinleProvider2Url) && !string.IsNullOrWhiteSpace(paperMailOnlinleProvider2DisplayName))
            {
                    <li>
                        <a href="@paperMailOnlinleProvider2Url" target="_blank">@paperMailOnlinleProvider2DisplayName</a>
                    </li>
                }
            </ul>
        </p>

        @if (Model.Instructions.CanMarkAsSent)
        {
            <div>
                @using (Html.BeginForm("MarkAsSent", "OutgoingVerification"))
                {
                    @Html.AntiForgeryToken()

                    <input type="hidden" name="verificationUniqueId" value="@Model.Instructions.VerificationUniqueId" />
                    <input type="hidden" name="returnToSummary" value="@Model.ReturnToSummary.ToString()" />
                    <button class="btn btn-success" type="submit"
                            title="@OutgoingVerificationResources.Instructions_ActionMarkAsSent_ButtonHoverText"
                            onclick="return confirm('@OutgoingVerificationResources.Instructions_ActionMarkAsSent_ButtonConfirmationText')">
                        @OutgoingVerificationResources.Instructions_ActionMarkAsSent_ButtonText
                    </button>
                }
            </div>
        }
    </div>
</div>

@using Epsilon.Logic.Constants
@using Epsilon.Resources.Common
@using Epsilon.Web.Controllers

<div>
    @if (Model.ReturnToSummary)
    {
        @Html.ActionLink(CommonResources.BackLinkText, OutgoingVerificationController.MY_OUTGOING_VERIFICATIONS_SUMMARY_ACTION)
    }
    else
    {
        @Html.ActionLink(CommonResources.BackLinkText, AppConstant.AUTHENTICATED_USER_HOME_ACTION, AppConstant.AUTHENTICATED_USER_HOME_CONTROLLER)
    }
</div>


Epsilon/Epsilon.Web/Views/OutgoingVerification/MyOutgoingVerificationsSummary.cshtml
@using Epsilon.Resources.Web.OutgoingVerification

@{
    ViewBag.Title = OutgoingVerificationResources.MyOutgoingVerificationsSummary_PageTitle;
}

<hr />

<div class="row">
    <my-outgoing-verifications-summary limit-items-returned="false" is-summary-page="true" allow-caching="false" />
</div>


Epsilon/Epsilon.Web/Views/OutgoingVerification/Pick.cshtml
@model Epsilon.Web.Models.ViewModels.OutgoingVerification.PickOutgoingVerificationViewModel

@using Epsilon.Resources.Web.OutgoingVerification
@using Epsilon.Resources.Common
@using Epsilon.Logic.Models
@using Epsilon.Logic.Constants

@{
    ViewBag.Title = OutgoingVerificationResources.Pick_PageTitle;

    var userInterfaceCustomisation = (UserInterfaceCustomisationModel)ViewBag.UserInterfaceCustomisation;
}

<h2>@OutgoingVerificationResources.Pick_Header</h2>


@using (Html.BeginForm("PickConfirmed", "OutgoingVerification"))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.VerificationUniqueId)
    @Html.HiddenFor(model => model.ReturnToSummary)

    <div class="form-horizontal">
        <div class="form-group">
            <label class="control-label col-md-3">@CommonResources.Country</label>
            <div class="col-md-9">
                <div class="form-control">
                    @AppConstant.COUNTRY_DISPLAY_FIELD_SELECTOR(userInterfaceCustomisation.UserResidenceCountry)
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="alert alert-info">
                <p>
                    @OutgoingVerificationResources.Pick_ConfirmationText
                </p>
            </div>
        </div>

        <div class="form-group">
            <div>
                <input type="submit" value="@OutgoingVerificationResources.Pick_SubmitButton"
                       class="btn btn-default"
                       data-click-once />
            </div>
        </div>
    </div>
}

Epsilon/Epsilon.Web/Views/OutgoingVerification/PrintableVerificationMessage.cshtml
@model Epsilon.Logic.Models.VerificationMessageArgumentsModel

@{
    Layout = null;
}

<h3>
    @Html.Partial("_VerificationMessage")
</h3>

Epsilon/Epsilon.Web/Views/OutgoingVerification/_VerificationMessage.cshtml
@model Epsilon.Logic.Models.VerificationMessageArgumentsModel
@using Epsilon.Logic.Constants.Enums
@using Epsilon.Logic.Constants
@using Epsilon.Logic.Helpers.Interfaces

@{ 
    var appSettingsHelper = DependencyResolver.Current.GetService<IAppSettingsHelper>();
    var applicationName = appSettingsHelper.GetString(AppSettingsKey.ApplicationName);
    var applicationWebAddress = appSettingsHelper.GetString(AppSettingsKey.ApplicationWebAddress);
}

@* EnumSwitch:CountryId *@
@switch (Model.CountryId)
{
    case CountryId.GB:
        @* ----------------------- GB ----------------------- *@
        <text>
            This is your verification mail from @(applicationName). <br />
            Your secret code is @(Model.SecretCode). <br />
            Go to @(applicationWebAddress),
            log in with the account you used when registering your address, and
            enter this code to verify your address.
        </text>
        @* -------------------------------------------------- *@
    break;

    case CountryId.GR:
        @* ----------------------- GR ----------------------- *@
        <text>
            Αυτό είναι το μήνυμα επιβεβαίωσης από την @(applicationName). <br />
            Ο κωδικός σου ειναι @(Model.SecretCode) (με λατινικούς χαρακτήρες). <br />
            Μπές στο @(applicationWebAddress) με τον λογαριασμό σου
            και επιβεβαίωσε την διεύθηνσή σου εισάγωντας αυτό τον κωδικό.
        </text>
        @* -------------------------------------------------- *@
        break;
    default:
        throw new NotImplementedException(string.Format("Unexpected CountryId: '{0}'", Model.CountryId));
}

Epsilon/Epsilon.Web/Views/OutgoingVerification/_VerificationRecipient.cshtml
@model Epsilon.Logic.Models.AddressModel
@using Epsilon.Logic.Entities.Interfaces
@using Epsilon.Logic.Constants.Enums
@using Epsilon.Logic.Constants.Interfaces
@using Epsilon.Logic.Constants.Interfaces.CountryAddressFieldMetadata

@{ 
    string theTenantLine = string.Empty;

    // EnumSwitch:CountryId 
    switch (Model.CountryIdAsEnum)
    {
        case CountryId.GB:
            theTenantLine = "The tenant";
            break;
        case CountryId.GR:
            theTenantLine = "Προς τον ένοικο";
            break;
        default:
            throw new NotImplementedException(string.Format("Unexpected CountryId: '{0}'", Model.CountryId));
    }

    var metadata = DependencyResolver.Current.GetService<ICountryAddressFieldMetadata>().GetForCountry(Model.CountryIdAsEnum);

    var pieces = new List<Tuple<FieldMetadata, string>> {
        Tuple.Create(metadata.Line1, Model.Line1),
        Tuple.Create(metadata.Line2, Model.Line2),
        Tuple.Create(metadata.Line3, Model.Line3),
        Tuple.Create(metadata.Line4, Model.Line4),
        Tuple.Create(metadata.Locality, Model.Locality),
        Tuple.Create(metadata.Region, Model.Region),
        Tuple.Create(metadata.Postcode, Model.Postcode)
    };
}

<p>
    @theTenantLine <br />
    @foreach (var p in pieces)
    {
        if (p.Item1.IsUsed && (p.Item1.IsRequired || !string.IsNullOrWhiteSpace(p.Item2)))
        {
            <text>@p.Item2</text> <br />
        }
    }
    @Model.CountryEnglishName
</p>