Epsilon/Epsilon.Web/Controllers/ApiControllers/TokenController.cs
using Epsilon.Logic.Helpers.Interfaces;
using Epsilon.Logic.JsonModels;
using Epsilon.Logic.Services.Interfaces;
using Epsilon.Web.Controllers.BaseControllers;
using System.Threading.Tasks;
using System.Web.Http;

namespace Epsilon.Web.Controllers.ApiControllers
{
    public class TokenController : BaseApiController
    {
        private readonly IUserTokenService _userTokenService;
        private readonly ITokenRewardService _tokenRewardService;

        public TokenController(
            IUserTokenService userTokenService,
            ITokenRewardMetadataHelper tokenRewardMetadataHelper,
            ITokenRewardService tokenRewardService)
        {
            _userTokenService = userTokenService;
            _tokenRewardService = tokenRewardService;
        }

        [HttpGet]
        public async Task<TokenBalanceResponse> Balance()
        {
            return await _userTokenService.GetBalance(GetUserId());
        }

        [HttpPost]
        public async Task<MyTokenTransactionsPageResponse> MyTokenTransactionsNextPage(MyTokenTransactionsPageRequest request)
        {
            return await _userTokenService.GetMyTokenTransactionsNextPage(GetUserId(), request);
        }

        [HttpGet]
        public TokenRewardMetadata TokenRewardMetadata()
        {
            return _tokenRewardService.GetAllTokenRewardMetadata();
        }

        [HttpGet]
        [AllowAnonymous]
        public TokenRewardsSummaryResponse TokenRewardsSummary()
        {
            return _tokenRewardService.GetTokenRewardsSummary();
        }
    }
}

Epsilon/Epsilon.Web/Controllers/DevHelperController.cs
using Epsilon.Logic.Constants;
using Epsilon.Logic.Helpers;
using Epsilon.Logic.Services.Interfaces;
using Epsilon.Logic.SqlContext.Interfaces;
using Epsilon.Logic.TestDataPopulation.Interfaces;
using Epsilon.Web.Controllers.BaseControllers;
using Epsilon.Web.Controllers.Filters.Mvc;
using Microsoft.AspNet.Identity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Epsilon.Web.Controllers
{
    [Authorize(Roles = AspNetRole.Admin)]
    [AllowIfConfigSettingTrue(AppSettingsKey.EnableDevHelperController)]
    public class DevHelperController : BaseMvcController
    {
        private readonly IEpsilonContext _dbContext;
        private readonly ITestDataPopulator _testDataPopulator;
        private readonly IAdminAlertService _adminAlertService;
        private readonly IUserTokenService _userTokenService;

        public DevHelperController(
            IEpsilonContext dbContext,
            ITestDataPopulator testDataPopulator,
            IAdminAlertService adminAlertService,
            IUserTokenService userTokenService)
        {
            _dbContext = dbContext;
            _testDataPopulator = testDataPopulator;
            _adminAlertService = adminAlertService;
            _userTokenService = userTokenService;
        }
        
        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> PopulateAddresses()
        { 
            await _testDataPopulator.Populate(User.Identity.GetUserId());

            Success("Addresses table has been populated!");

            return RedirectToAction("Index");
        }

        public ActionResult SuccessAlert()
        {
            Success("This is a <b>Success</b> alert.", false);
            return RedirectToAction("Index");
        }

        public ActionResult SuccessAlertDismissable()
        {
            Success("This is a dismissable <b>Success</b> alert.", true);
            return RedirectToAction("Index");
        }

        public ActionResult WarningAlert()
        {
            Warning("This is a <b>Warning</b> alert.", false);
            return RedirectToAction("Index");
        }

        public ActionResult WarningAlertDismissable()
        {
            Warning("This is a dismissable <b>Warning</b> alert.", true);
            return RedirectToAction("Index");
        }

        public ActionResult InformationAlert()
        {
            Information("This is an <b>Information</b> alert.", false);
            return RedirectToAction("Index");
        }

        public ActionResult InformationAlertDismissable()
        {
            Information("This is a dismissable <b>Information</b> alert.", true);
            return RedirectToAction("Index");
        }

        public ActionResult DangerAlert()
        {
            Danger("This is a <b>Danger</b> alert.", false);
            return RedirectToAction("Index");
        }

        public ActionResult DangerAlertDismissable()
        {
            Danger("This is a dismissable <b>Danger</b> alert.", true);
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SendAdminAlert(string adminAlertKey)
        {
            _adminAlertService.SendAlert(adminAlertKey);
            Success(string.Format("AdminAlert for key '{0}' sent.", adminAlertKey), true);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<ActionResult> Tokens()
        {
            var balance = await _userTokenService.GetBalance(GetUserId());

            ViewBag.TokenRewardKey = 
                EnumsHelper.TokenRewardKey.GetNames().Select(x => new SelectListItem() { Text = x, Value = x }).ToList();

            return View(balance);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> TokensTransaction(
            string tokenRewardKey,
            int quantity)
        {
            var tokenRewardKeyEnum = EnumsHelper.TokenRewardKey.Parse(tokenRewardKey);
            if (tokenRewardKeyEnum.HasValue)
            {
                var status = await _userTokenService.MakeTransaction(GetUserId(), tokenRewardKeyEnum.Value, quantity: quantity);
            }

            return RedirectToAction("Tokens");
        }
    }
}

Epsilon/Epsilon.Web/Controllers/TokenController.cs
using Epsilon.Web.Controllers.BaseControllers;
using System.Web.Mvc;

namespace Epsilon.Web.Controllers
{
    public class TokenController : BaseMvcController
    {
        public ActionResult Transactions()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult Rewards()
        {
            return View();
        }
    }
}

Epsilon/Epsilon.Web/Views/DevHelper/Coins.cshtml
@model Decimal
@{
    ViewBag.Title = "Coins";
}

<h2>Coins</h2>

<div class="row">
    <div class="col-md-4">
        <h3>Balance</h3>
        @Model
    </div>
    <div class="col-md-4">
        <h3>Credit</h3>
        @using (Html.BeginForm("CoinsCredit", "DevHelper"))
        {
            @Html.AntiForgeryToken()
            <input type="number" name="amount" />
            <input type="submit" class="btn btn-default" />
        }
    </div>
    <div class="col-md-4">
        <h3>Debit</h3>
        @using (Html.BeginForm("CoinsDebit", "DevHelper"))
        {
            @Html.AntiForgeryToken()
            <input type="number"name="amount" />
            <input type="submit" class="btn btn-default" />
        }
    </div>
</div>


Epsilon/Epsilon.Web/Views/DevHelper/Index.cshtml
@{
    ViewBag.Title = "Helper Tools";
}

<div class="row">
    <div class="col-md-4">
        <h2>Test the alerts</h2>
        <p><a class="btn btn-default btn-success" href="@Url.Action("SuccessAlert")">Success</a>
           <a class="btn btn-default btn-success" href="@Url.Action("SuccessAlertDismissable")">Success Dismissable</a></p>
        <p><a class="btn btn-default btn-warning" href="@Url.Action("WarningAlert")">Warning</a>
           <a class="btn btn-default btn-warning" href="@Url.Action("WarningAlertDismissable")">Warning Dismissable</a></p>
        <p><a class="btn btn-default btn-info" href="@Url.Action("InformationAlert")">Information</a>
           <a class="btn btn-default btn-info" href="@Url.Action("InformationAlertDismissable")">Information Dismissable</a></p>
        <p><a class="btn btn-default btn-danger" href="@Url.Action("DangerAlert")">Danger</a>
           <a class="btn btn-default btn-danger" href="@Url.Action("DangerAlertDismissable")">Danger Dismissable</a></p>
    </div>
    <div class="col-md-4">
        <h2>Test data</h2>
        <p>Populate the database.</p>
        <p><a class="btn btn-default" href="@Url.Action("PopulateAddresses")">Addresses</a></p>
    </div>
    <div class="col-md-4">
        <h2>Links</h2>
        @Html.ActionLink("Tokens", "Tokens")
    </div>
</div>

@using Epsilon.Logic.Helpers.Interfaces
<div class="row">
    <div class="col-md-3">
        <h2>Testing area</h2>
        @using Epsilon.Logic.Constants.Enums
        @using Epsilon.Logic.Helpers
        @{ 
            var countryVariantResourceHelper = DependencyResolver.Current.GetService<ICountryVariantResourceHelper>();
            var postcodeVariants = countryVariantResourceHelper.GetVariants(new List<CountryVariantResourceName> {
                CountryVariantResourceName.Address_Postcode });
        } 
        @foreach (var countryId in postcodeVariants.Keys)
        {
            var names = postcodeVariants[countryId].Keys;
            foreach (var name in names)
            {
            <p>@countryId : @name : @(postcodeVariants[countryId][name])</p>
            }
        }
    </div>
    <div class="col-md-3">
        <h2>Send Admin Alert</h2>
        @using (Html.BeginForm("SendAdminAlert", "DevHelper"))
        {
            @Html.AntiForgeryToken()
            <input type="text" name="adminAlertKey" />
            <input type="submit" class="btn btn-default" />
        }
    </div>
</div>

Epsilon/Epsilon.Web/Views/DevHelper/Tokens.cshtml
@model Epsilon.Logic.JsonModels.TokenBalanceResponse
@{
    ViewBag.Title = "Tokens";
}

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-md-4">
        <h3>Balance</h3>
        @Model.balance
    </div>
    <div class="col-md-8">
        <h3>Credit</h3>
        @using (Html.BeginForm("TokensTransaction", "DevHelper"))
        {
            @Html.AntiForgeryToken()

            <div class="form-group">
                <label class="control-label col-md-3" for="TokenRewardType">Token Reward Type</label>
                <div class="col-md-9">
                    @Html.DropDownList("TokenRewardKey", ViewBag.TokenRewardKey as IEnumerable<SelectListItem>, new { @class = "form-control"})
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-3" for="quantity">Quantity</label>
                <div class="col-md-9">
                    <input type="number" class="form-control" name="quantity" />
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-3 col-md-9">
                    <input type="submit" class="btn btn-default" />
                </div>
            </div>
        }
    </div>
</div>
