Epsilon/Epsilon.Web/Models/ViewModels/TextResource/ListViewModel.cs
using Epsilon.Logic.Entities;
using Epsilon.Logic.Helpers.Interfaces;
using System.Collections.Generic;

namespace Epsilon.Web.Models.ViewModels.TextResource
{
    public class ListViewModel
    {
        public IList<LocalizedResource> Resources { get; set; }
        public string CultureCode { get; set; }
        public IList<Language> Languages { get; set; }
    }
}

Epsilon/Epsilon.Web/Controllers/TextResourceController.cs
using Epsilon.Logic.Constants;
using Epsilon.Logic.Helpers.Interfaces;
using Epsilon.Logic.Services.Interfaces;
using Epsilon.Logic.Wrappers.Interfaces;
using Epsilon.Web.Controllers.BaseControllers;
using Epsilon.Web.Models.ViewModels.TextResource;
using System.IO;
using System.Text;
using System.Web.Mvc;

namespace Epsilon.Web.Controllers
{
    [Authorize(Roles = AspNetRole.AdminOrTranslator)]
    public class TextResourceController : BaseMvcController
    {
        private readonly IClock _clock;
        private readonly ITextResourceHelper _textResourceHelper;
        private readonly ILanguageService _languageService;

        public TextResourceController(
            IClock clock,
            ITextResourceHelper textResourceHelper,
            ILanguageService languageService)
        {
            _clock = clock;
            _textResourceHelper = textResourceHelper;
            _languageService = languageService;
        }

        public ActionResult List(string id)
        {
            var cultureCode = id;

            var model = new ListViewModel
            {
                Resources = _textResourceHelper.AllResources(cultureCode),
                CultureCode = cultureCode,
                Languages = _languageService.GetAvailableAndUnavailableLanguages()
                
            };
            return View(model);
        }

        public ActionResult Download(string id)
        {
            var cultureCode = id;
            using (var stream = new StringWriter())
            {
                _textResourceHelper.AllResourcesCsv(cultureCode, stream);

                var contentType = AppConstant.CONTENT_TYPE_CSV;
                var bytes = Encoding.UTF8.GetBytes(stream.ToString());
                var result = new FileContentResult(bytes, contentType);
                result.FileDownloadName = 
                    string.Format("Resources_UTC{0}_{1}.csv", 
                    _clock.OffsetUtcNow.ToString(AppConstant.DATE_TIME_FORMAT_FOR_FILENAME), 
                    cultureCode ?? "default");
                return result;
             }
        }
    }
}

Epsilon/Epsilon.Web/Views/TextResource/List.cshtml
@model Epsilon.Web.Models.ViewModels.TextResource.ListViewModel

@{
    ViewBag.Title = "Text Resources";
}

<h2>@ViewBag.Title</h2>

<p>

    @{
        var selectedLabelClass = "label-primary";
        var notSelectedLabelClass = "label-warning";
    }

    <a class="label @(Model.CultureCode == null ? selectedLabelClass : notSelectedLabelClass)"
       href="@Url.Action("List", "TextResource", new { id = (string)null })">
        Default
    </a>
    <text>&nbsp;</text>
    @foreach (var language in Model.Languages)
    {
        var labelClass = Model.CultureCode != null && Model.CultureCode.ToLowerInvariant().Equals(language.CultureCode.ToLowerInvariant())
            ? selectedLabelClass : notSelectedLabelClass;
        <a class="label @labelClass"
           href="@Url.Action("List", "TextResource", new { id = language.CultureCode })">
            @language.EnglishName
        </a>
        <text>&nbsp;</text>
    }
</p>

<p>
    <a href="@Url.Action("Download", "TextResource", new { id = Model.CultureCode})" 
       class="btn btn-primary">
        Download CSV
    </a>
</p>


@foreach (var resource in Model.Resources)
{
    <div class="panel panel-success">
        <div class="panel-heading"><h4>@resource.Type</h4></div>
        <div class="panel-body">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Default</th>
                        @if (Model.CultureCode != null)
                        {
                        <th>Local</th>
                        }
                    </tr>
                </thead>
                <tbody>
                    @foreach (var entry in resource.Entries)
                    {
                        <tr>
                            <td>
                                @entry.Name
                            </td>
                            <td>
                                @entry.DefaultValue
                            </td>
                            @if (Model.CultureCode != null)
                            {
                            <td>
                                @entry.LocalizedValue
                            </td>
                            }
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
}







